# Generated by Django 5.0.6 on 2024-07-07 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ap1.product'),
        ),
    ]
