# Generated by Django 5.0.6 on 2024-07-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap1', '0002_alter_bill_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='product',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
