# Generated by Django 5.0.6 on 2024-07-07 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap1', '0003_alter_bill_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ap1.product'),
        ),
    ]
