# Generated by Django 5.0.6 on 2024-07-07 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap1', '0004_alter_bill_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totalamount',
            name='total',
        ),
        migrations.AddField(
            model_name='totalamount',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='totalamount',
            name='transaction_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ap1.bill'),
        ),
    ]
