# Generated by Django 5.0.6 on 2024-07-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap1', '0005_remove_totalamount_total_totalamount_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalamount',
            name='transaction_id',
            field=models.IntegerField(),
        ),
    ]
